mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    # Decided to make tutor_me the root of the site
    path('', include('tutor_me.urls')),
]

tutor_me/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

app_name = 'tutor_me'
urlpatterns = [
    path('home', TemplateView.as_view(template_name="tutor_me/index.html"), name='home'),
    path('', views.user_redirect , name='main'),
    path('clear_class', views.clear_class, name='clear_class'),
    path('<int:user_id>/', views.index_view, name='user_home'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('<int:user_id>/select_class/', views.select_class, name='select_class'),
    path('retrieve_course_for_dept/<str:dept>/', views.retrieve_courses_for_dept, name='retrieve_courses_for_dept'),
    path('courses/<str:dept>/', views.CourseView.as_view(), name='courses'),
    path('<int:user_id>/select_courses/', views.select_courses, name='select_courses'),
    path('courses/', views.CourseView.as_view(), name='courses'),
    path('tutor_list/', views.TutorListView.as_view(), name='tutors'),
    path('tutor_list/<str:course>/', views.TutorListView.as_view(), name='tutors'),
    path('<int:user_id>/profile/', views.edit_profile_view, name='edit_profile'),
    path('<int:user_id>/profile/', views.profile, name='profile'), 
    path('<int:user_id>/profile/send_request/', views.send_request, name='send_request'), 
    path('remove_course/<int:courseID>', views.remove_course, name='remove_course'),
    path('<int:user_id>/profile/add_availability/', views.add_availability, name='add_availability'),
    path('accept_request/<int:requestID>', views.accept_request, name='accept_request'),
    path('decline_request/<int:requestID>', views.decline_request, name='decline_request'),
    path('cancel_booking/<int:booking_id>', views.cancel_booking, name='cancel_booking'),
    path('delete_availability/<int:availability_id>', views.delete_availability, name='delete_availability'),
]

tutor_me/models.py
from django.db import models
from django.contrib.auth.models import User as auth_user


# from django.contrib.postgres.fields import ArrayField

# Create your models here.

class TM_User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    is_tutor = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    auth_user = models.OneToOneField(auth_user, on_delete=models.CASCADE, null=True)
    courses = models.ManyToManyField('Course', blank=True)
    calendar_exists = models.BooleanField(default=False)

    friends = models.ManyToManyField('TM_User', blank=True)

    calendar_id = models.CharField(max_length=200, blank=True, null=True, default='')
    calendar_url = models.CharField(max_length=200, blank=True, null=True, default='')

    # add more fields as needed
    hourly_rate = models.IntegerField(default=0)
    age = models.IntegerField(default=0)

    availability = models.ManyToManyField('Time_Range', blank=True)

    reviews = models.ManyToManyField('Review', blank=True)

    def __str__(self):
        return f'{self.name} ({self.email})'


class FriendRequest(models.Model):
    from_user = models.ForeignKey(TM_User, related_name="from_user", on_delete=models.CASCADE)
    to_user = models.ForeignKey(TM_User, related_name="to_user", on_delete=models.CASCADE)
    booking = models.ForeignKey('Booking', on_delete=models.CASCADE, null=True)

class Booking(models.Model):
    tutor = models.ForeignKey(TM_User, on_delete=models.CASCADE, related_name='tutor')
    student = models.ForeignKey(TM_User, on_delete=models.CASCADE, related_name='student')
    time = models.ForeignKey('Time_Range', on_delete=models.CASCADE, related_name='time')
    course = models.ForeignKey('Course', on_delete=models.CASCADE, related_name='course')
    approved = models.BooleanField(default=False)
    friend_request = models.ForeignKey('FriendRequest', on_delete=models.SET_NULL, related_name='friend_request', null=True)
    cancelled = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.student.name} booked {self.tutor.name} for {self.course} at {self.time.to_string()}'


class Course(models.Model):
    department = models.CharField(max_length=4)
    course_number = models.CharField(max_length=4)
    course_description = models.CharField(max_length=1000)
    tutors = models.ManyToManyField('TM_User', blank=True)

    def __str__(self):
        return f'{self.department} {self.course_number}'  


class Dept(models.Model):
    dept = models.CharField(max_length=4)
    courses = models.ManyToManyField('Course', blank=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.dept}'

    # add more fields as needed


class Time_Range(models.Model):
    start = models.DateTimeField(blank=True)
    end = models.DateTimeField(blank=True)

    def to_string(self):
        return f'{self.start.strftime("%m/%d/%Y %I:%M %p")} to {self.end.strftime("%m/%d/%Y %I:%M %p")}'

    def __str__(self):
        return f'{self.start} {self.end}'


class Review(models.Model):
    commenter = models.ForeignKey(TM_User, on_delete=models.CASCADE, related_name='commenter')
    target = models.ForeignKey(TM_User, on_delete=models.CASCADE, related_name='target')
    text = models.CharField(blank=True, max_length=500)

    def __str__(self):
        return f'{self.commenter}\'s review of {self.target.name}'

tutor_me/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User as auth_user
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import EditProfileForm, EditProfileForm_Tutor, ReviewForm, AvailabilityForm


from .models import TM_User, Course, Dept, FriendRequest, Review, Booking, Time_Range
from datetime import datetime, timedelta
import pytz


def send_request(request, user_id):
    print(f'request.POST: {request.POST}')
    from_user_ = auth_user.objects.get(id = request.user.id)
    from_user = TM_User.objects.get(auth_user = from_user_)
    start_time = datetime.strptime(request.POST['startDateTime'],"%Y-%m-%dT%H:%M")
    start_time = start_time.replace(tzinfo=pytz.timezone('UTC'))
    hours_dur = int(request.POST['duration'][:2])
    minutes_dur = int(request.POST['duration'][3:])
    # n_hours = hours_dur + start_time.hour
    # n_minutes = minutes_dur + start_time.minute
    # if n_minutes >= 60:
    #     n_hours += 1
    #     n_minutes -= 60
    duration = timedelta(hours=hours_dur, minutes=minutes_dur)
    end_time = start_time + duration
    # end_time = start_time.replace(hour=n_hours, minute=n_minutes)
    # end_time = datetime(end_time.year, end_time.month, end_time.day, end_time.hour, end_time.minute, end_time.second, tzinfo=start_time.tzinfo)
    # time_range = Time_Range.objects.create(start=start_time, end=end_time)
    # to_user = TM_User.objects.get(id=user_id)

    # # check if it falls in the availability of the tutor
    # availabilities = to_user.availability.all()
    # for availability in availabilities:
    #     if time_range.start >= availability.start and time_range.end <= availability.end:
    #         break
    # else:
    #     return HttpResponse('Tutor is not available at that time <a href=' + reverse('tutor_me:edit_profile', args=(to_user.auth_user.id,)) + ">Go Back</a>")

    # # check if the tutor is already booked at that time
    # bookings = Booking.objects.filter(tutor=to_user)
    # for booking in bookings:
    #     if time_range.start < booking.time.start and time_range.start > booking.time.end or time_range.end < booking.time.start and time_range.end > booking.time.end:
    #         return HttpResponse('Tutor is already booked at that time')
    
    # course_l = request.POST['course'].strip().split()
    # course = Course.objects.get(department=course_l[0], course_number=course_l[1])
    # friend_request = FriendRequest.objects.create(from_user=from_user, to_user=to_user)
    # booking, created = Booking.objects.get_or_create(tutor=to_user, student=from_user, approved=False, friend_request=friend_request, time=time_range, course=course)
    # friend_request.booking = booking
    # friend_request.save()
    if request.POST['recurring'] == 'False':
        created = create_request_and_booking(start_time, end_time, user_id, from_user, request.POST['course'])
    else:
        for i in range(int(request.POST['count'])):
            created = create_request_and_booking(start_time, end_time, user_id, from_user, request.POST['course'])
            if not created:
                break
            if request.POST['frequency'] == 'weekly':
                start_time = start_time + timedelta(days=7)
                end_time = end_time + timedelta(days=7)
            elif request.POST['frequency'] == 'biweekly':
                start_time = start_time + timedelta(days=14)
                end_time = end_time + timedelta(days=14)
            elif request.POST['frequency'] == 'monthly':
                start_time = start_time + timedelta(days=30)
                end_time = end_time + timedelta(days=30)
    if created: 
        return HttpResponseRedirect(reverse('tutor_me:user_home', args=(request.user.id,)))
    else:
        return HttpResponse('Tutoring Request Was Already Sent')

def create_request_and_booking(start_time, end_time, user_id, from_user, course):
    time_range = Time_Range.objects.create(start=start_time, end=end_time)
    to_user = TM_User.objects.get(id=user_id)

    # check if it falls in the availability of the tutor
    availabilities = to_user.availability.all()
    for availability in availabilities:
        if time_range.start >= availability.start and time_range.end <= availability.end:
            break
    else:
        return HttpResponse('Tutor is not available at that time <a href=' + reverse('tutor_me:edit_profile', args=(to_user.auth_user.id,)) + ">Go Back</a>")

    # check if the tutor is already booked at that time
    bookings = Booking.objects.filter(tutor=to_user)
    for booking in bookings:
        if time_range.start < booking.time.start and time_range.start > booking.time.end or time_range.end < booking.time.start and time_range.end > booking.time.end:
            return HttpResponse('Tutor is already booked at that time')
    
    course_l = course.strip().split()
    course = Course.objects.get(department=course_l[0], course_number=course_l[1])
    friend_request = FriendRequest.objects.create(from_user=from_user, to_user=to_user)
    booking, created = Booking.objects.get_or_create(tutor=to_user, student=from_user, approved=False, friend_request=friend_request, time=time_range, course=course)
    friend_request.booking = booking
    friend_request.save()
    return created

def decline_request(request, requestID):
    friend_request = FriendRequest.objects.get(id=requestID)
    if (friend_request.to_user == request.user.tm_user) or (friend_request.from_user == request.user.tm_user):
        friend_request.booking.delete()
        return HttpResponse(f"Tutoring Request {'Declined' if request.user.tm_user.is_tutor else 'Deleted'} for {friend_request.from_user.name} <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")
    else:
        return HttpResponse(f"Tutoring Request NOT {'Declined' if request.user.tm_user.is_tutor else 'Deleted'} <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")

def accept_request(request, requestID):
    friend_request = FriendRequest.objects.get(id=requestID)
    if (friend_request.to_user == request.user.tm_user):
        friend_request.to_user.friends.add(friend_request.from_user)
        friend_request.from_user.friends.add(friend_request.to_user)
        print(friend_request.booking)
        if friend_request.booking.approved:
            return HttpResponse(f"Tutoring Request Already Accepted for {friend_request.from_user.name} <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")
        for booking in Booking.objects.filter(student=friend_request.from_user, approved=True, cancelled=False):
            if booking.time.start < friend_request.booking.time.start < booking.time.end or booking.time.end > friend_request.booking.time.end > booking.time.start:
                return HttpResponse(f"Tutoring Request Overlaps with {booking.student.name}'s Session with {booking.tutor.name} <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")
        for booking in Booking.objects.filter(tutor=friend_request.from_user, approved=True, cancelled=False):
            if booking.time.start < friend_request.booking.time.start < booking.time.end or booking.time.end > friend_request.booking.time.end > booking.time.start:
                return HttpResponse(f"Tutoring Request Overlaps with {booking.student.name}'s Session with {booking.tutor.name} <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")
        friend_request.booking.approved = True
        friend_request.booking.save()
        friend_request.delete()
        return HttpResponseRedirect(reverse('tutor_me:user_home', args=(request.user.id,))) # HttpResponse(f"Tutoring Request Accepted for {friend_request.from_user.name} <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")
    else:
        return HttpResponse("Tutoring Request Not Accepted <a href=" + reverse('tutor_me:user_home', args=(request.user.id,)) + ">Go Back</a>")

def user_redirect(request):
    print(f'request.user.id: {request.user.id}')
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('tutor_me:user_home', args=(request.user.id,)))
    else:
        return HttpResponseRedirect(reverse('tutor_me:home'))

def remove_course(request, courseID):
    user = request.user.tm_user
    course = Course.objects.get(id=courseID)
    user.courses.remove(course)
    course.tutors.remove(user)
    return HttpResponseRedirect(reverse('tutor_me:profile', args=(request.user.id,)))

class IndexView(generic.DetailView):
    model = TM_User
    template_name = 'tutor_me/index.html'

    def get_context_data(self, **kwargs):
        print(f'self.request: {self.request}')
        context = super().get_context_data(**kwargs)
        obj_requests = FriendRequest.objects.filter(to_user=self.request.user.tm_user)
        requests_formatted = []
        for requesti in obj_requests:
            requests_formatted.append(f'Request from {requesti.from_user.name}')
        context['requests'] = requests_formatted
        if self.request.user.tm_user.is_tutor:
            obj_sessions = Booking.objects.filter(tutor=self.request.user.tm_user)
            context['sessions'] = obj_sessions
        else:
            obj_sessions = Booking.objects.filter(student=self.request.user.tm_user)
            context['sessions'] = obj_sessions
        print(len(obj_sessions))
        return context

def index_view(request, user_id):
    if user_id != request.user.id:
        return HttpResponseRedirect(reverse('tutor_me:user_home', args=(request.user.id,)))
    user = get_object_or_404(auth_user, id=user_id)
    try:
        tm_user = get_object_or_404(TM_User, auth_user=user)
    except:

tutor_me/templates/tutor_me/course.html
{% load socialaccount %}
{% load bootstrap5 %}
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="../../static/tutor_me/tutor_me.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@500&family=Poppins&family=Raleway:wght@500&display=swap" rel="stylesheet">


<html>
    <title>TutorMe</title>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #7692FF">
        <div class="navbar-collapse" id="navbarSupportedContent">
            <a class="nav-link" href="{% url 'tutor_me:main' %}"><img src="../../static/tutor_me/images/Group 4.png" width="30" height="30" alt="" class="navbar-logo"></a>
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:main' %}">TutorMe</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:courses' %}">Courses</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:profile' user.id %}">Profile</a></li>
            </ul>
            {% endif %}
        </div>
        <div class="navbar-collapse justify-content-end" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0" action="{% url 'tutor_me:courses' %}" style="display: flex;">
                <input class="form-control mr-sm-2" name="dept" placeholder="Search for a department" style="margin-right: 5px;">
                <button class="btn btn-info my-2 my-sm-0" style="color: white" type="submit">Search</button>
            </form>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:logout' %}">Logout</a></li>
                {% else %}
                    <form action="{% provider_login_url 'google' %}" class="form-button">
                        <button type="submit" class="submit-button"><img src="{% static 'tutor_me/images/Google__G__Logo 2.png' %}" alt="Image" width="20px" height="20px"/> Login with Google</button>
                    </form>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% if dept %}
    <div style="width: 600px; margin: 0 auto;">
        <h2 style="text-align: center; padding: 40px; color: #084b83; font-size: xx-large">Tutors for {{ dept }} Courses:</h2>
<!--        <input style="width: 400px; margin-left: 120px"; class="form-control" id="classes" type="text" placeholder="Enter Course Number..." onkeyup="searchCourse()"><br>-->
        <script>
            function searchCourse() {
                var text = document.getElementById('classes').value, lis = document.querySelectorAll('#list li'), x;

                for (x=0; x<lis.length; x++) {
                    if (text === '' || lis[x].innerHTML.indexOf(text) > -1) {
                        lis[x].removeAttribute('hidden');
                    } else {
                        lis[x].setAttribute('hidden', true);
                    }
                }
            }
        </script>
        {% if tm_user.is_tutor %}
        <p style="text-align: center; font-weight: bolder; color: darkcyan; font-family: 'Raleway', sans-serif; font-size: medium;">Select the courses that you are a tutor for and click submit: </p>
        <form action="{% url 'tutor_me:select_courses' user.id %}" method="post" style="margin-left: 45px;">
            {% csrf_token %}
            <div style="overflow: scroll; scrollbar: cadetblue; max-height: 550px; background-color: mintcream; border-radius: 20px; padding-bottom: 20px; padding-top: 20px">
                {% for course in course_list %}
                <ul id="list-group">
                        <div class="form-check">
                            <li style="list-style-type: none; padding: 0; padding-right: 20px; margin: 0;">
                                <input class="form-check-input" name="courses" type="checkbox" value="{{course.id}}">
                                    <label class="form-check-label" for="courses">{{course}} - {{course.course_description}}</label><br>
                                        {% if course.tutors.all %}
                                            <label style="color: #65cbc4; font-family: 'Raleway', sans-serif; font-weight: bold; margin-top: 10px">Available Tutors: </label><br>
                                            {% for t in course.tutors.all %}
                                                <button class="btn btn-info btn-sm" style="margin-bottom: 4px; background-color: #6c7ae4 !important; border-color: #6c7ae4 !important">
                                                        <a href="{% url 'tutor_me:profile' t.auth_user.id %}" style="text-decoration: none !important; color: white">{{t.name}}</a>
                                                </button>
                                            {% endfor %}
                                        {% endif %}
                                </input>
                            </li>
                        </div>
                </ul>
                {% endfor %}
            </div>

            <input type="submit" value="Submit" class="form-submit"><br><br>
            {% comment %} <ul>
                {% for course in course_list %}
                    <li>{{course}}</li>
                {% endfor %}
            </ul> {% endcomment %}
        </form>
    </div>
        {% else %}
        <p style="text-align: center; font-weight: bolder; color: darkcyan; font-family: 'Raleway', sans-serif; font-size: medium;">Choose tutors from each corresponding course to view their profiles:</p>
        <div style="max-height: 400px; overflow: scroll; background-color: beige">
            <ul class="list-group" style="background-color: mintcream">
                    {% for course in course_list %}
                    <li class="list-group-item" style="background-color: mintcream">
                    <div class="d-flex w-100 justify-content-between align-items-center">
                        {{ course }} - {{ course.course_description }}
                    </div>
                    <ul class="list-unstyled">
                        {% if course.tutors.all %}
                            <label style="color: #65cbc4; font-family: 'Raleway', sans-serif; font-weight: bolder; margin-top: 10px">Available Tutors: </label><br>
                        {% endif %}
                        {% for t in course.tutors.all %}
                        <button class="btn btn-info btn-sm" style="margin-bottom: 4px; background-color: #6c7ae4 !important; border-color: #6c7ae4 !important">
                            <a href="{% url 'tutor_me:profile' t.auth_user.id %}" style="text-decoration: none !important; color: white">{{t.name}}</a>
                        </button>
                        {% endfor %}
                    </ul>
                    </li>
                {% endfor %}
                </ul>
        </div>
    {% endif %}
    {% endif %}

    </div>




</body>
</html>

tutor_me/templates/tutor_me/depts.html
{% load socialaccount %}
{% load bootstrap5 %}
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="../../static/tutor_me/tutor_me.css">
<link href="https://unpkg.com/bootstrap-table@1.21.4/dist/bootstrap-table.min.css" rel="stylesheet">

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>


<html>
    <title>TutorMe</title>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #7692FF">
        <div class="navbar-collapse" id="navbarSupportedContent">
            <a class="nav-link" href="{% url 'tutor_me:main' %}"><img src="../../static/tutor_me/images/Group 4.png" width="30" height="30" alt="" class="navbar-logo"></a>
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:main' %}">TutorMe</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:courses' %}">Courses</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:profile' user.id %}">Profile</a></li>
            </ul>
            {% endif %}
        </div>
        <div class="navbar-collapse justify-content-end" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0" action="{% url 'tutor_me:courses' %}" style="display: flex;">
                <input class="form-control mr-sm-2" name="dept" placeholder="Search for a department" style="margin-right: 5px;">
                <button class="btn btn-info my-2 my-sm-0" style="color: white" type="submit">Search</button>
            </form>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:logout' %}">Logout</a></li>
                {% else %}
                    <form action="{% provider_login_url 'google' %}" class="form-button">
                        <button type="submit" class="submit-button"><img src="{% static 'tutor_me/images/Google__G__Logo 2.png' %}" alt="Image" width="20px" height="20px"/> Login with Google</button>
                    </form>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% if bad_search %}
        <div class="alert alert-danger" role="alert">
            <strong>Sorry!</strong> We couldn't find any courses for that department. Please select from the below list.
        </div>
    {% endif %}
    <h1 style="text-align: center; padding: 40px; color: #084b83">Select Course Department</h1>
    <input style="width: 600px; margin: 0 auto" class="form-control" id="dept" type="text" placeholder="Enter Department Mnemonic...">
    <br>
    <ul class="list-group" style="list-style: none; columns: 50px 2; width: 600px; margin: 0 auto; max-height: 600px; overflow: scroll">
            <table class="table" id="dept-table" data-toggle="table" data-search="true" data-url="dept-list" style="box-shadow: 1px 1px 1px #999;">
                {% for dept in dept_list %}
                    <thead>
                        <tr>
                            <td><a style="font-size: 20px; margin: 10px; padding: 5px; display: inline-block; text-decoration: none;" href="{% url 'tutor_me:courses' %}?dept={{ dept }}">{{ dept }} {{ dept.}}</a></td>
                        </tr>
                    </thead>
                {% endfor %}
            </table>
    </ul>
    <script>
        $(document).ready(function() {
            $("#dept").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#dept-table tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
</body>
</html>

tutor_me/templates/tutor_me/tutors_list.html
{% load socialaccount %}
{% load bootstrap5 %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="../../static/tutor_me/tutor_me.css">

<html>
<body>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #7692FF">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <img src="../../static/tutor_me/images/Group 4.png" width="30" height="30" alt="" class="navbar-logo">
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:main' %}">TutorMe</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:courses' %}">Courses</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:profile' user.id %}">Profile</a></li>
            </ul>
            {% endif %}
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0" action="{% url 'tutor_me:courses' %}">
                <input class="form-control mr-sm-2" name="dept" placeholder="Search for a department" style="margin-right: 5px;">
                <button class="btn btn-info my-2 my-sm-0" style="color: white" type="submit">Search</button>
            </form>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'tutor_me:logout' %}">Logout</a></li>
                {% else %}
                    <form action="{% provider_login_url 'google' %}" class="form-button">
                        <button type="submit" class="submit-button"><img src="../../static/tutor_me/images/Google__G__Logo%202.png" alt="Image" width="20px" height="20px"/> Login with Google</button>
                    </form>
                {% endif %}
            </ul>
        </div>
    </nav>

    <h2>Tutors for {{ course }}</h2>
    <!-- {% for user in TM_User.objects.values %}
        {% if user.is_tutor %}
            {{user.name}}
        {% endif %}
    {% endfor %} -->
    {% comment %}
        - Output a list through all the tutors who have added this course in their profile
        - allow for the user to click on each tutor to go to their profile
    {% endcomment %}

</body>
</html>